name = "KJ"
uuid = "c976074e-2e5b-4ac6-9301-394412a2f0b0"
version = "0.8.1"
authors = ["pvermees <p.vermeesch@ucl.ac.uk>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Dates = "1.11.0"
Distributions = "0.25.123"
FiniteDiff = "2.29.0"
ForwardDiff = "1.3.1"
GR = "0.73.19"
Infiltrator = "1.9.7"
LinearAlgebra = "1.12.0"
Optim = "2.0.0"
Plots = "1.41.4"
Printf = "1.11.0"
Statistics = "1.11.1"
